[project]
name = "ai-agent"
version = "0.1.0"
description = "Extendable AI Agent framework built with Python and Google GenAI SDK"
readme = "README.md"
authors = [
    { name = "WIJAYATHUNGA R.S.C.W.M.T.B.K.", email = "thatilawijayathunga@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.20.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ai-agent = "ai_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
