[project]
name = "ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "WIJAYATHUNGA R.S.C.W.M.T.B.K.", email = "thatilawijayathunga@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ai-agent = "ai_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
